### PR TITLE
Create GH action to build swt

### PR DESCRIPTION
**Pull request by laeubi**

### CODE REVIEW

**Comment by laeubi** [comment]
@akurtakov do you have any idea why I get under windows

```
Can't load library: D:\a\eclipse.platform.swt\eclipse.platform.swt\tests\org.eclipse.swt.tests\target\.swt\lib\win32\x86_64\swt-gtk-4952r10.dll
Can't load library: D:\a\eclipse.platform.swt\eclipse.platform.swt\tests\org.eclipse.swt.tests\target\.swt\lib\win32\x86_64\swt-gtk.dll
Can't load library: D:\a\eclipse.platform.swt\eclipse.platform.swt\tests\org.eclipse.swt.tests\target\.swt\lib\win32\x86_64\swt.dll 
```

Do I need to enable/checkout something special here?

**Comment by akurtakov** [comment]
Yes, you need platform.swt.binaries too. You can see at https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/Jenkinsfile#L90 the checkout of the extra repo and https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/Jenkinsfile#L102 building/installing the rebuilt natives for use after that for the tests.

**Comment by laeubi** [comment]
Ah... I missed that, thnaks I'll try that out. Do you know where I can find the name of the "natives" I guessed them as

- native: gtk.linux.x86_64
- native: win32.win32.x86_64
- cocoa.macosx.x86_64

I'm just curious why it works for linux without explicit checkout of the natives...

**Comment by akurtakov** [comment]
> Ah... I missed that, thnaks I'll try that out. Do you know where I can find the name of the "natives" I guessed them as

https://github.com/eclipse-platform/eclipse.platform.swt.binaries/blob/master/pom.xml#L56 is the best place as it lists swt ports that are actively being built.

> I'm just curious why it works for linux without explicit checkout of the natives...

I see that it works for macos too. So it might be the fact that gcc/llvm being available by default on these OSes while Windows needing Visual Studio and probably some extra configuration to be a "good" build machine. I have no idea how recent https://www.eclipse.org/swt/swt_win_native.php is. @niraj-modi should be able to help with more info.

**Comment by laeubi** [comment]
I actually don't want to  *build* the natives, so though it should be possible to just use the pre build binaries.

The macos build also fails, but is green as I igore test failures, windows seem to be a bit more strict and crashing the whole maven build, linux "just works" on the commandline.

**Comment by akurtakov** [comment]
> I actually don't want to _build_ the natives, so though it should be possible to just use the pre build binaries.
> 
> The macos build also fails, but is green as I igore test failures, windows seem to be a bit more strict and crashing the whole maven build, linux "just works" on the commandline.

In this case remove "-Dnative=..." this is explicit request to *rebuild* the native parts.

**Comment by akurtakov** [comment]
This skipRust part makes nothing as nothing uses rust in swt anymore.

**Comment by laeubi** [comment]
Hm.. this seems something else, even though I now install the native parts I get:

> 	Can't load library: D:\a\eclipse.platform.swt\eclipse.platform.swt\eclipse.platform.swt\tests\org.eclipse.swt.tests\target\.swt\lib\win32\x86_64\swt-gtk-4952r10.dll
> 	Can't load library: D:\a\eclipse.platform.swt\eclipse.platform.swt\eclipse.platform.swt\tests\org.eclipse.swt.tests\target\.swt\lib\win32\x86_64\swt-gtk.dll
> 	Can't load library: D:\a\eclipse.platform.swt\eclipse.platform.swt\eclipse.platform.swt\tests\org.eclipse.swt.tests\target\.swt\lib\win32\x86_64\swt.dll

**Comment by akurtakov** [comment]
Is this one done?

**Comment by laeubi** [comment]
Yeah this was jaust an experiemnt and I already have migrated the code to the main SWT repository...

**Pull request closed without merging**
